name:                hexamplestreaming
version:             1.0.0
github:              "JoergBrueggmann/hexamplestreaming"
license:             "CC0-1.0-Deed"
author:              "Jörg Karl-Heinz Walter Brüggmann"
maintainer:          "info@joerg-brueggmann.de"
copyright:           "No Copyright"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JoergBrueggmann/hexamplestreaming#readme>

dependencies:
- base >= 4.7 && < 5
- streaming
- echo

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hexamplestreaming:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hexamplestreaming

tests:
  hexamplestreaming-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hexamplestreaming
